/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update product
         * @description Replaces all editable fields of an existing product.
         *     Images are replaced only when new files are provided. Omitting `images` preserves existing ones.
         *     Updating `name` always regenerates the slug.
         */
        put: operations["updateProduct"];
        post?: never;
        /**
         * Delete product
         * @description Soft-deletes a product by setting its `deletedAt` timestamp.
         *     The product is no longer returned by catalog endpoints.
         *     This operation is not reversible via the API.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products
         * @description Returns a paginated list of active products, optionally filtered by category.
         *     Results are cached by `categoryId + page + size + sort`.
         */
        get: operations["getAllProducts"];
        put?: never;
        /**
         * Create product
         * @description Creates a new product and uploads the provided images to Cloudinary.
         *     Uses `multipart/form-data` with two parts: `data` (JSON) and `images` (files).
         *     Files and metadata are matched by index: `images[0]` → `data.images[0]`.
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Wompi webhook event
         * @description Public endpoint used exclusively by Wompi to notify transaction status updates.
         *     Secured via SHA-256 signature validation instead of JWT.
         */
        post: operations["handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment status by order
         * @description Retrieves the current payment record associated with the specified order.
         *
         *     ## Polling Strategy
         *
         *     Poll every **3 seconds** with a max timeout of **5 minutes** until
         *     a final state is reached: `APPROVED`, `DECLINED`, `ERROR`, or `VOIDED`.
         */
        get: operations["getPaymentByOrder"];
        put?: never;
        /**
         * Create pending payment for an order
         * @description Creates a new pending payment associated with the specified order.
         *
         *     This endpoint **must be called before** opening the Wompi Checkout Widget.
         *     The returned `reference` is required by Wompi to correlate the transaction.
         *
         *     ## PSE — Redirect Required
         *
         *     For PSE payments the response includes a `redirectUrl`.
         *     For `CARD` and `NEQUI`, `redirectUrl` is absent.
         */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description Returns a paginated list of orders. The result set depends on the caller's role:
         *
         *     | Role | Visible orders |
         *     |------|----------------|
         *     | `ADMIN` | All orders in the system |
         *     | `BUYER` | Only their own orders |
         */
        get: operations["getAllOrders"];
        put?: never;
        /**
         * Create order
         * @description Creates a new order from the provided items and sets it to `PENDING_PAYMENT`.
         *
         *     ## Stock Validation
         *
         *     For each item, stock is validated at creation time:
         *     - Products with `UNLIMITED` stock type skip validation.
         *     - Products with `AVAILABLE` or `MADE_TO_ORDER` stock must have enough units.
         *       If not, the entire request is rejected.
         *
         *     ## Pricing
         *
         *     `unitPrice` is captured at the moment the order is created.
         *     Price changes after order creation do not affect existing orders.
         *
         *     ## Next Step
         *
         *     After creating the order, call `POST /payments/orders/{orderId}` to initiate
         *     payment via the Wompi Checkout Widget.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all categories
         * @description Retrieves all categories currently available in the catalog.
         *
         *     ## Usage
         *
         *     Categories can be used to:
         *
         *     - Populate navigation menus
         *     - Build category filters
         *     - Organize products in the storefront
         *
         *     ## Ordering
         *
         *     Categories are returned according to the repository default ordering.
         *
         *     ## Authentication
         *
         *     This endpoint is public and does not require authentication.
         */
        get: operations["getAll"];
        put?: never;
        /**
         * Create category
         * @description Creates a new product category.
         *
         *     ## Authorization
         *
         *     Only users with the `ADMIN` role can create categories.
         *
         *     ## Slug Uniqueness
         *
         *     The provided slug must be unique across all existing categories.
         *
         *     Attempting to create a category using an already existing slug
         *     results in a conflict response.
         *
         *     ## Catalog Impact
         *
         *     Newly created categories become immediately available
         *     for product classification and catalog browsing.
         *
         *     ## Best Practices
         *
         *     Slugs should:
         *
         *     - Be lowercase
         *     - Use hyphens instead of spaces
         *     - Remain stable over time
         *
         *     Example:
         *
         *     - Name: `Home Decoration`
         *     - Slug: `home-decoration`
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register new account
         * @description Creates a new user account and immediately returns
         *     authenticated session tokens.
         *
         *     ## Default Role
         *
         *     Newly registered users are assigned the `BUYER` role.
         *
         *     Administrative accounts cannot be created through this endpoint.
         *
         *     ## Automatic Authentication
         *
         *     After registration:
         *
         *     - Access token is generated
         *     - Refresh token is generated
         *     - User is considered authenticated
         *
         *     No additional login request is required.
         *
         *     ## Email Uniqueness
         *
         *     Email addresses must be unique across all accounts.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Generates a new authenticated session using a valid refresh token.
         *
         *     ## Token Rotation
         *
         *     Refresh tokens are single-use.
         *
         *     When a refresh succeeds:
         *
         *     - Previous refresh token is revoked
         *     - New access token is issued
         *     - New refresh token is issued
         *
         *     Clients must replace stored tokens with the newly returned values.
         *
         *     ## Security
         *
         *     Reusing an old refresh token is not allowed.
         *
         *     ## Account Restrictions
         *
         *     Refresh requests are rejected for banned users.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout user
         * @description Terminates the current authenticated session.
         *
         *     ## Session Revocation
         *
         *     The provided refresh token is validated and all active
         *     refresh tokens belonging to the user are revoked.
         *
         *     After logout:
         *
         *     - Existing refresh tokens become unusable
         *     - New access tokens cannot be generated
         *
         *     Users must authenticate again to create a new session.
         *
         *     ## Access Tokens
         *
         *     Previously issued access tokens remain valid until expiration.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user
         * @description Authenticates a registered user using email and password credentials.
         *
         *     ## Successful Authentication
         *
         *     When authentication succeeds, the API returns:
         *
         *     - JWT access token
         *     - Refresh token
         *     - User role
         *     - Token expiration time
         *
         *     ## Security
         *
         *     Passwords are validated against securely stored password hashes.
         *
         *     ## Rate Limiting
         *
         *     Failed login attempts are rate limited.
         *
         *     After too many failed attempts, authentication is temporarily
         *     blocked for approximately 5 minutes.
         *
         *     ## Account Restrictions
         *
         *     Authentication is denied if the user account has been banned.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle product visibility
         * @description Flips the `isActive` flag of a product.
         *     - `isActive: true` → visible in catalog
         *     - `isActive: false` → hidden from buyers, not deleted
         */
        patch: operations["toggleActive"];
        trace?: never;
    };
    "/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order status
         * @description Updates the status of an order. Allowed transitions differ by role:
         *
         *     | Role | Allowed transition | Precondition |
         *     |------|--------------------|--------------|
         *     | `ADMIN` | Any `PAID` → `SHIPPED` | Order must be in `PAID` status |
         *     | `BUYER` | Own order `PENDING_PAYMENT` → `CANCELLED` | Order must be in `PENDING_PAYMENT` status |
         */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/admin/users/{id}/unban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Unban user
         * @description Restores access to a previously banned user account.
         *
         *     ## Purpose
         *
         *     Removes the banned flag from the specified user and restores the account
         *     to its normal operational state.
         *
         *     ## Idempotency
         *
         *     Calling this endpoint multiple times for a user that is already active
         *     produces the same final state.
         *
         *     ## Authorization
         *
         *     Only users with the `ADMIN` role can perform this action.
         *
         *     ## Audit Impact
         *
         *     User data is preserved. Only the moderation status is updated.
         */
        patch: operations["unbanUser"];
        trace?: never;
    };
    "/admin/users/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Ban user
         * @description Restricts a user account by marking it as banned.
         *
         *     ## Purpose
         *
         *     This operation is intended for moderation and administrative actions.
         *
         *     Once banned, the user account is flagged internally and may lose access
         *     to authenticated functionality depending on platform authorization rules.
         *
         *     ## Idempotency
         *
         *     Calling this endpoint multiple times for an already banned user
         *     produces the same final state.
         *
         *     ## Authorization
         *
         *     Only users with the `ADMIN` role can perform this action.
         *
         *     ## Audit Impact
         *
         *     User data is preserved. Only the moderation status is updated.
         */
        patch: operations["banUser"];
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product by slug
         * @description Returns a single product identified by its URL-friendly slug.
         *     Example: `"Handmade Ceramic Mug"` → `"handmade-ceramic-mug"`.
         */
        get: operations["getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/financial-institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available PSE financial institutions
         * @description Retrieves the list of financial institutions currently supported by Wompi for PSE.
         *     Call this before rendering the PSE payment form to populate the bank selector.
         */
        get: operations["getFinancialInstitutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order by ID
         * @description Returns a specific order by its UUID.
         *
         *     - `ADMIN` can retrieve any order.
         *     - `BUYER` can only retrieve their own orders.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my orders
         * @description Returns the full order history of the authenticated user, sorted
         *     by creation date descending (most recent first).
         *
         *     This endpoint is available to all roles. Each user sees only their own orders.
         */
        get: operations["getMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard statistics
         * @description Returns the main metrics displayed in the administrative dashboard.
         *
         *     ## Sales Calculation
         *
         *     `totalSalesThisMonth` includes all sales generated since the first day
         *     of the current UTC month.
         *
         *     ## Pending Orders
         *
         *     Counts orders currently in the `PENDING_PAYMENT` status.
         *
         *     ## Active Products
         *
         *     Counts products where `isActive = true`.
         *
         *     ## Top Selling Product
         *
         *     Returns the product with the highest accumulated quantity sold.
         *
         *     If no products have been sold yet, `topSellingProduct` is returned as `null`.
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Represents an image associated with a product */
        ProductImageRequest: {
            /**
             * @description Indicates whether this image is the main (primary) product image
             * @example true
             */
            isPrimary: boolean;
            /**
             * Format: int32
             * @description Display order of the image (lower values appear first)
             * @example 0
             */
            sortOrder?: number;
        };
        /** @description Product data as JSON */
        ProductRequest: {
            /**
             * Format: uuid
             * @description Category UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            categoryId: string;
            /** @example Handmade Ceramic Mug */
            name: string;
            /** @example Beautiful handmade mug */
            description?: string;
            /** @example Crafted by local artisans... */
            story?: string;
            /** @example 49.99 */
            price: number;
            /**
             * @example AVAILABLE
             * @enum {string}
             */
            stockType: "UNLIMITED" | "AVAILABLE" | "MADE_TO_ORDER";
            /**
             * Format: int32
             * @description Stock quantity. Required for AVAILABLE and MADE_TO_ORDER stock types
             * @example 10
             */
            stockQuantity?: number;
            /** @example false */
            isCustomOrder: boolean;
            /** @example true */
            isActive: boolean;
            images?: components["schemas"]["ProductImageRequest"][];
        };
        /**
         * @description Represents an image associated with a product returned by the API
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440001",
         *       "url": "https://res.cloudinary.com/artelier/image/upload/v1712345678/products/mug.jpg",
         *       "cloudinaryId": "products/mug_abc123",
         *       "isPrimary": true,
         *       "sortOrder": 0
         *     }
         */
        ProductImageResponse: {
            /**
             * Format: uuid
             * @description Unique identifier of the product image
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            id?: string;
            /**
             * @description Public URL of the image
             * @example https://res.cloudinary.com/artelier/image/upload/v1712345678/products/mug.jpg
             */
            url?: string;
            /**
             * @description Cloudinary public ID used to manage the image
             * @example products/mug_abc123
             */
            cloudinaryId?: string;
            /**
             * @description Indicates whether this image is the primary product image
             * @example true
             */
            isPrimary?: boolean;
            /**
             * Format: int32
             * @description Display order of the image (lower values appear first)
             * @example 0
             */
            sortOrder?: number;
        };
        /**
         * @description Represents a product category returned by the API
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440000",
         *       "name": "Ceramics",
         *       "slug": "ceramics",
         *       "description": "Handmade ceramic products including mugs and bowls"
         *     }
         */
        CategoryResponse: {
            /**
             * Format: uuid
             * @description Unique identifier of the category
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /**
             * @description Display name of the category
             * @example Ceramics
             */
            name?: string;
            /**
             * @description URL-friendly identifier used in routes
             * @example ceramics
             */
            slug?: string;
            /**
             * @description Optional description explaining the category
             * @example Handmade ceramic products including mugs and bowls
             */
            description?: string;
        };
        /**
         * @description Represents a product returned by the API, including category and images
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440000",
         *       "category": {
         *         "id": "550e8400-e29b-41d4-a716-446655440111",
         *         "name": "Ceramics",
         *         "slug": "ceramics",
         *         "description": "Handmade ceramic products"
         *       },
         *       "name": "Handmade Ceramic Mug",
         *       "slug": "handmade-ceramic-mug",
         *       "description": "Beautiful handmade ceramic mug",
         *       "story": "Crafted by local artisans using traditional techniques",
         *       "price": 49.99,
         *       "stockType": "FINITE",
         *       "stockQuantity": 10,
         *       "isCustomOrder": false,
         *       "isActive": true,
         *       "createdAt": "2026-01-15T10:30:00Z",
         *       "images": [
         *         {
         *           "id": "550e8400-e29b-41d4-a716-446655440001",
         *           "url": "https://res.cloudinary.com/artelier/image/upload/v1712345678/products/mug.jpg",
         *           "cloudinaryId": "products/mug_abc123",
         *           "isPrimary": true,
         *           "sortOrder": 0
         *         }
         *       ]
         *     }
         */
        ProductResponse: {
            /**
             * Format: uuid
             * @description Unique identifier of the product
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /** @description Category to which the product belongs */
            category?: components["schemas"]["CategoryResponse"];
            /**
             * @description Product display name
             * @example Handmade Ceramic Mug
             */
            name?: string;
            /**
             * @description SEO-friendly slug used in URLs
             * @example handmade-ceramic-mug
             */
            slug?: string;
            /**
             * @description Short product description
             * @example Beautiful handmade ceramic mug
             */
            description?: string;
            /**
             * @description Optional story or background about the product
             * @example Crafted by local artisans using traditional techniques
             */
            story?: string;
            /**
             * @description Product price
             * @example 49.99
             */
            price?: number;
            /**
             * @description Defines how stock is handled
             * @enum {string}
             */
            stockType?: "UNLIMITED" | "AVAILABLE" | "MADE_TO_ORDER";
            /**
             * Format: int32
             * @description Available stock quantity. Relevant only for AVAILABLE and MADE_TO_ORDER stock types
             * @example 10
             */
            stockQuantity?: number;
            /**
             * @description Indicates whether the product supports custom orders
             * @example false
             */
            isCustomOrder?: boolean;
            /**
             * @description Indicates whether the product is active and visible
             * @example true
             */
            isActive?: boolean;
            /**
             * Format: date-time
             * @description Timestamp when the product was created
             * @example 2026-01-15T10:30:00Z
             */
            createdAt?: string;
            /** @description List of images associated with the product */
            images?: components["schemas"]["ProductImageResponse"][];
        };
        ProductResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["ProductResponse"];
        };
        /** @description Standard API response wrapper used for all endpoints */
        ApiResponse: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: unknown;
        };
        /** @description Webhook payload recibido desde Wompi cuando cambia el estado de una transacción */
        PaymentWebhookRequest: {
            /**
             * @description Tipo de evento de Wompi
             * @example transaction.updated
             */
            event?: string;
            /** @description Wrapper del payload de la transacción */
            data?: components["schemas"]["TransactionData"];
            /** @description Datos de firma para validar autenticidad del webhook */
            signature?: components["schemas"]["SignatureData"];
            /**
             * Format: int64
             * @description Unix timestamp del evento en milisegundos
             * @example 1715000000000
             */
            timestamp?: number;
        };
        /** @description Bloque de firma HMAC para verificar autenticidad del webhook */
        SignatureData: {
            /**
             * @description Checksum SHA-256 generado por Wompi
             * @example a3f5c9d8e1b2...
             */
            checksum?: string;
            /**
             * @description Lista de propiedades usadas para generar la firma
             * @example [
             *       "transaction.id",
             *       "transaction.status",
             *       "transaction.amount_in_cents"
             *     ]
             */
            properties?: string[];
        };
        /** @description Datos de la transacción de Wompi */
        Transaction: {
            /**
             * @description ID único de la transacción en Wompi
             * @example 1292-1602113476-10985
             */
            id?: string;
            /**
             * @description Referencia del comercio
             * @example ORDER-550e8400-1715000000000
             */
            reference?: string;
            /**
             * @description Estado de la transacción
             * @example APPROVED
             * @enum {string}
             */
            status?: "PENDING" | "APPROVED" | "DECLINED" | "VOIDED" | "ERROR";
            /**
             * @description Método de pago usado por el cliente
             * @example NEQUI
             * @enum {string}
             */
            payment_method_type?: "CARD" | "NEQUI" | "PSE" | "BANCOLOMBIA_TRANSFER" | "BANCOLOMBIA_QR";
            /**
             * Format: int64
             * @description Monto en centavos
             * @example 100000
             */
            amount_in_cents?: number;
        };
        /** @description Wrapper de la transacción */
        TransactionData: {
            /** @description Detalle de la transacción */
            transaction?: components["schemas"]["Transaction"];
        };
        /** @description Credit or debit card payment. */
        CardPaymentMethod: Omit<WithRequired<components["schemas"]["PaymentMethodBody"], "type">, "type"> & {
            /**
             * @description Payment method type.
             * @example CARD
             */
            type: string;
            /**
             * @description Card token generated previously by Wompi.
             * @example tok_prod_123456
             */
            token: string;
            /**
             * Format: int32
             * @description Number of installments selected by the customer.
             * @example 1
             */
            installments?: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CARD";
        };
        /** @description Customer personal data. */
        CustomerData: {
            /** @example María García */
            full_name?: string;
            /** @example +573001112233 */
            phone_number?: string;
        };
        /** @description Nequi payment. */
        NequiPaymentMethod: Omit<WithRequired<components["schemas"]["PaymentMethodBody"], "type">, "type"> & {
            /**
             * @description Payment method type.
             * @example NEQUI
             */
            type: string;
            /**
             * @description Nequi account phone number.
             * @example 3107654321
             */
            phone_number: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NEQUI";
        };
        /** @description Payment method information. */
        PaymentMethodBody: {
            type: string;
        };
        /** @description Request to initiate a payment for an order. */
        PaymentRequest: {
            /** @description Payment method chosen by the customer. */
            payment_method: components["schemas"]["CardPaymentMethod"] | components["schemas"]["NequiPaymentMethod"] | components["schemas"]["PsePaymentMethod"];
            /** @description Optional customer info (name, phone). Required for PSE. */
            customer_data?: components["schemas"]["CustomerData"];
        };
        /** @description PSE bank transfer payment. */
        PsePaymentMethod: Omit<WithRequired<components["schemas"]["PaymentMethodBody"], "type">, "type"> & {
            /**
             * @description Payment method type.
             * @example PSE
             */
            type: string;
            /**
             * Format: int32
             * @description Person type. Natural person (0) or legal entity (1).
             * @example 0
             */
            user_type: number;
            /**
             * @description Document type (CC, CE, NIT, etc.).
             * @example CC
             */
            user_legal_id_type: string;
            /**
             * @description Customer document number.
             * @example 1099888777
             */
            user_legal_id: string;
            /**
             * @description Financial institution code returned by Wompi.
             * @example 1
             */
            financial_institution_code: string;
            /**
             * @description Payment description. Maximum 64 characters.
             * @example Payment for Artelier order #123
             */
            payment_description: string;
            /**
             * @description Customer IP address (financial services anti-fraud field).
             * @example 192.168.0.1
             */
            reference_one?: string;
            /**
             * @description Financial product opening date in yyyyMMdd format.
             * @example 20240101
             */
            reference_two?: string;
            /**
             * @description Financial product beneficiary document number.
             * @example 12345678
             */
            reference_three?: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "PSE";
        };
        /** @description Payment response payload. */
        PaymentResponse: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            orderId?: string;
            /** @example 1292-1602113476-10985 */
            wompiTransactionId?: string;
            /** @example ORDER-550e8400-1715000000000 */
            reference?: string;
            /**
             * @description Current payment status.
             * @enum {string}
             */
            status?: "PENDING" | "APPROVED" | "DECLINED" | "VOIDED" | "ERROR";
            /** @example 120000.00 */
            amount?: number;
            /**
             * @example NEQUI
             * @enum {string}
             */
            paymentMethod?: "CARD" | "NEQUI" | "PSE";
            /** @description Redirect URL for PSE or Bancolombia. Frontend must redirect user here. */
            redirectUrl?: string;
            /** Format: date-time */
            paidAt?: string;
        };
        PaymentResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["PaymentResponse"];
        };
        /** @description Single item inside an order */
        OrderItemRequest: {
            /**
             * Format: uuid
             * @description Product UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            productId: string;
            /**
             * Format: int32
             * @description Quantity of the product
             * @example 2
             */
            quantity?: number;
            /**
             * @description Optional customization notes for this item
             * @example No onions, extra cheese
             */
            customNotes?: string;
        };
        /** @description Request payload for creating a new order */
        OrderRequest: {
            /** @description List of items included in the order */
            items: components["schemas"]["OrderItemRequest"][];
            /**
             * @description Shipping address for the order
             * @example Cra 123 #45-67, Bogotá, Colombia
             */
            shippingAddress: string;
            /**
             * @description Optional notes for the order
             * @example Please deliver after 5 PM
             */
            notes?: string;
        };
        /** @description Represents a single item in an order response */
        OrderItemResponse: {
            /**
             * Format: uuid
             * @description Product UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            productId?: string;
            /**
             * @description Product name
             * @example Handmade Ceramic Mug
             */
            productName?: string;
            /**
             * Format: int32
             * @description Quantity ordered
             * @example 2
             */
            quantity?: number;
            /**
             * @description Unit price at the time of purchase
             * @example 29.99
             */
            unitPrice?: number;
            /**
             * @description Optional notes for this item
             * @example Gift wrap this item
             */
            customNotes?: string;
        };
        /** @description Represents an order response */
        OrderResponse: {
            /**
             * Format: uuid
             * @description Order UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /**
             * @description Current status of the order
             * @example PENDING_PAYMENT
             * @enum {string}
             */
            status?: "PENDING_PAYMENT" | "PAID" | "PROCESSING" | "SHIPPED" | "CANCELLED";
            /**
             * @description Subtotal amount
             * @example 59.98
             */
            subtotal?: number;
            /**
             * @description Total amount (including taxes, shipping, etc.)
             * @example 59.98
             */
            total?: number;
            /**
             * @description Shipping address
             * @example Cra 123 #45-67, Bogotá, Colombia
             */
            shippingAddress?: string;
            /**
             * @description Optional notes
             * @example Leave at the door
             */
            notes?: string;
            /**
             * Format: date-time
             * @description Order creation timestamp
             * @example 2026-05-04T15:30:00Z
             */
            createdAt?: string;
            /** @description List of items in the order */
            items?: components["schemas"]["OrderItemResponse"][];
        };
        OrderResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["OrderResponse"];
        };
        /** @description Category creation request */
        CategoryRequest: {
            /**
             * @description Display name of the category
             * @example Ceramics
             */
            name: string;
            /**
             * @description URL-friendly unique identifier
             * @example ceramics
             */
            slug: string;
            /**
             * @description Optional category description
             * @example Handmade ceramic products including mugs and bowls
             */
            description?: string;
        };
        CategoryResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["CategoryResponse"];
        };
        /** @description User registration request */
        RegisterRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example StrongPass123 */
            password: string;
            /** @example John Doe */
            fullName: string;
            /** @example +573001234567 */
            phone?: string;
        };
        /** @description Response returned after successful authentication containing JWT tokens and session metadata */
        AuthResponse: {
            /**
             * @description JWT access token used to authenticate API requests
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.accessTokenExample123456789
             */
            token?: string;
            /**
             * @description User role assigned to the authenticated user
             * @example BUYER
             * @enum {string}
             */
            role?: "ADMIN" | "BUYER";
            /**
             * @description Refresh token used to obtain new access tokens without re-authentication
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.refreshTokenExample987654321
             */
            refreshToken?: string;
            /**
             * Format: int64
             * @description Access token expiration time in seconds
             * @example 3600
             */
            expiresIn?: number;
        };
        AuthResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["AuthResponse"];
        };
        /** @description Request used to obtain a new JWT access token using a valid refresh token */
        RefreshRequest: {
            /**
             * @description Valid refresh token issued during login or previous refresh
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.refreshTokenExample1234567890
             */
            refreshToken: string;
        };
        /** @description Login credentials */
        LoginRequest: {
            /**
             * Format: email
             * @description User email
             * @example user@example.com
             */
            email: string;
            /**
             * @description User password
             * @example StrongPass123
             */
            password: string;
        };
        PageProductResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ProductResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        ProductPageResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["PageProductResponse"];
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        FinancialInstitutionsResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["WompiFinancialInstitutionsResponse"][];
        };
        WompiFinancialInstitutionsResponse: {
            financial_institution_code?: string;
            financial_institution_name?: string;
        };
        OrderPageResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["PageOrderResponse"];
        };
        PageOrderResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["OrderResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        OrderListResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["OrderResponse"][];
        };
        CategoryListResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["CategoryResponse"][];
        };
        StatsResponse: {
            totalSalesThisMonth?: number;
            /** Format: int64 */
            pendingOrders?: number;
            /** Format: int64 */
            activeProducts?: number;
            topSellingProduct?: components["schemas"]["TopProduct"];
        };
        StatsResponseBody: {
            /**
             * @description Indicates whether the request was successful
             * @example true
             */
            success?: boolean;
            /**
             * @description Human-readable message describing the result
             * @example Product created successfully
             */
            message?: string;
            /** @description Response payload containing requested data (nullable when no data is returned) */
            data?: components["schemas"]["StatsResponse"];
        };
        TopProduct: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int64 */
            totalSold?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Product UUID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    data: components["schemas"]["ProductRequest"];
                    /** @description Replacement image files. Omit to keep existing images. */
                    images?: string[];
                };
            };
        };
        responses: {
            /** @description Product updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseBody"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Access Denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Product or category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Product not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Image upload to Cloudinary failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Product UUID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Access Denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Product not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getAllProducts: {
        parameters: {
            query?: {
                /**
                 * @description Filter by category UUID.
                 * @example 660e8400-e29b-41d4-a716-446655440001
                 */
                categoryId?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPageResponseBody"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    data: components["schemas"]["ProductRequest"];
                    /** @description Product image files (coordinated by index with data.images) */
                    images?: string[];
                };
            };
        };
        responses: {
            /** @description Product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseBody"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Access Denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Category not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Image upload to Cloudinary failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    handleWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentWebhookRequest"];
            };
        };
        responses: {
            /** @description Webhook event successfully received and processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed webhook payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid Wompi signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPaymentByOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the order
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment record found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseBody"];
                };
            };
            /** @description No payment found for the specified order */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Payment not found for order"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the order to be paid
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description Pending payment created — ready to initiate Wompi Checkout */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseBody"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Order not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getAllOrders: {
        parameters: {
            query?: {
                /**
                 * @description Filter by order status. Optional — omit to return all statuses.
                 * @example PAID
                 */
                status?: "PENDING_PAYMENT" | "PAID" | "PROCESSING" | "SHIPPED" | "CANCELLED";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders retrieved — content filtered by role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPageResponseBody"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Items, shipping address, and optional notes */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Order created — status is PENDING_PAYMENT */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseBody"];
                };
            };
            /** @description Validation failed or insufficient stock */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponseBody"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Category data */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Category created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseBody"];
                };
            };
            /** @description Access denied — ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Slug already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseBody"];
                };
            };
            /** @description Invalid registration data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseBody"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
            /** @description User account is banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Logout completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Login credentials */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseBody"];
                };
            };
            /** @description Too many failed login attempts */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description User account is banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    toggleActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Product UUID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visibility toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseBody"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Access Denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Product not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query: {
                /** @description Target status */
                status: "PENDING_PAYMENT" | "PAID" | "PROCESSING" | "SHIPPED" | "CANCELLED";
            };
            header?: never;
            path: {
                /**
                 * @description Order UUID
                 * @example 770e8400-e29b-41d4-a716-446655440002
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseBody"];
                };
            };
            /** @description Transition not allowed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Buyer attempted to modify another user's order */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Access denied to this order"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Order not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    unbanUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description User UUID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User successfully restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Access denied — ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    banUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description User UUID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User successfully marked as banned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Access denied — ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description URL-friendly product identifier
                 * @example handmade-ceramic-mug
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponseBody"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Product not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getFinancialInstitutions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Financial institutions retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialInstitutionsResponseBody"];
                };
            };
            /** @description Unable to retrieve financial institutions — Wompi error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Order UUID
                 * @example 770e8400-e29b-41d4-a716-446655440002
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseBody"];
                };
            };
            /** @description Buyer attempted to access another user's order */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Access denied to this order"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Order not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getMyOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order history retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponseBody"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponseBody"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Access denied - ADMIN role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "Access Denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
